### ISSUE TITLE
Lab 3 / restoration

### ISSUE THREAD

**Issue by pierre-yves-monnet** [camunda-consulting/c8-devops-workshop#16]
having a Lab to back up and never playing the restoration is too bad, especialy because there is no REST API to restore Zeebe, but it has to be done via a command.
1/ we should start the cluster with 

```
  clusterSize: 3
  partitionCount: 3
  replicationFactor: 3
```

to be more realistic

There is an excellent document  started by:
DRI: [Stefan Wiese](mailto:stefan.wiese@camunda.com) | Contributors: [Tobias Stegemann](mailto:tobias.stegemann@camunda.com) [David Paroulek](mailto:david.paroulek@camunda.com) [Falko Menge](mailto:falko.menge@camunda.com)  [Christophe Dame](mailto:christophe.dame@camunda.com) [Paul Lungu](mailto:paul.lungu@camunda.com)

It shows how to configure the backup config for Zeebe and how to restore it. It does not show the complete backup procedure for the whole product stack!

(sorry, I didn't retrieve the URL, we should ask Stefan)

It will be nice to create a step, because the cluster is created by Helm: how to restore then? Create a custom Deployment, maybe, and start it? This deployment may just contain the restore part (no need to have an init container).

**Comment by j-lindner** [comment]
The mentioned excellent doc: https://docs.google.com/document/d/16rHtbavxJU7KuyBjgT0_NPQvieAiReFfAbxRW8Nb9gs/edit#heading=h.ct4eck1q9lyq

**Comment by jonathanlukas** [comment]
Done via https://github.com/camunda-consulting/c8-devops-workshop/commit/4e65ba6e595b6387a639232cae6dd21f2f6524cb

**Comment by ManuelDittmar** [comment]
Hi @jonathanlukas thanks for taking the initiative. To be honest I don't agree with having a setup with 3 brokers. For a lot of participants this means they cannot perform the exercise because they run on a local machine with one node. Of course you could also adjust the pod affinity, but I would prefer to keep the exercises as simple as possible. Also for implementing new features / exercises in the training I think we should establish a review process and not just merge into the main branch.

**Comment by jonathanlukas** [comment]
Hi @ManuelDittmar I agree with both proposals.

Therefore, I will set the cluster settings to 111 for this exercise.

For future FR implementations, I will use PRs
